@startuml
skinparam Shadowing false
skinparam NoteBorderColor #f3f1f6
skinparam NoteBackgroundColor #f3f1f6
skinparam NoteFontSize 12
skinparam ActivityBorderColor none
skinparam ActivityBackgroundColor #7a8da1
skinparam ActivityFontSize 16
skinparam ArrowColor #7aab8a
skinparam ArrowFontSize 16
skinparam ActivityDiamondBackgroundColor #7aab8a
skinparam ActivityDiamondBorderColor #7aab8a
skinparam ActivityDiamondFontSize 18
skinparam defaultFontName DejaVu Serif Condensed
skinparam ActivityEndColor #669580

header
<b>FV2210
2022-12-12
endheader

title
GPKE

6.44.1: AD Reklamation einer Konfiguration vom MSB



end title
:<b>E_0554</b>;
note right
<b><i>Prüfende Rolle: MSB
end note

if (<b>20: </b> Ist der Wirkungszeitraum bereits eingetreten?) then (ja)
else (nein)
    :A02;
    note left
        Cluster: Ablehnung
        Wirkungszeitraum noch nicht eingetreten
    endnote
    kill;
endif
if (<b>30: </b> Ist die Reklamation der Konfiguration berechtigt?) then (ja)
else (nein)
    :A03;
    note left
        Cluster: Ablehnung
        Reklamation unbegründet. Bestellte Konfiguration ist eingerichtet
    endnote
    kill;
endif
if (<b>40: </b> Kann die Konfiguration korrigiert werden?) then (ja)
else (nein)
    :A04;
    note left
        Cluster: Ablehnung
        Konfiguration kann trotz Bestellung nicht vorgenommen werden 
        Hinweis: Das identifizierte Problem ist in der Antwort zu beschreiben/benennen.
    endnote
    kill;
endif
if (<b>50: </b> Kann die Konfiguration sofort korrigiert werden?) then (ja)
    :A05;
    note left
        Cluster: Zustimmung
        Konfiguration wurde sofort angepasst
    endnote
    kill;
else (nein)
    :A06;
    note left
        Cluster: Zustimmung
        Konfiguration konnte nicht sofort korrigiert werden.
        Hinweis: Geplanter Behebungszeitpunkt muss angegeben werden.
    endnote
    kill;
endif

@enduml
