@startuml
skinparam Shadowing false
skinparam NoteBorderColor #f3f1f6
skinparam NoteBackgroundColor #f3f1f6
skinparam NoteFontSize 12
skinparam ActivityBorderColor none
skinparam ActivityBackgroundColor #7a8da1
skinparam ActivityFontSize 16
skinparam ArrowColor #7aab8a
skinparam ArrowFontSize 16
skinparam ActivityDiamondBackgroundColor #7aab8a
skinparam ActivityDiamondBorderColor #7aab8a
skinparam ActivityDiamondFontSize 18
skinparam defaultFontName DejaVu Serif Condensed
skinparam ActivityEndColor #669580

header
<b>FV2210
2022-12-12
endheader

title
GPKE

6.51.1: AD Reklamation einer Definition des LF vom NB an LF



end title
:<b>E_0550</b>;
note right
<b><i>Prüfende Rolle: LF
end note

if (<b>20: </b> Reklamiert der Absender das Fehlen der ausgerollten Schaltzeitdefinition?) then (ja)
    if (<b>30: </b> Entspricht der Code der Schaltzeitdefinition einem Code aus der für den reklamierten Zeitraum gültigen Übersicht der Schaltzeitdefinitionen?) then (ja)
    else (nein)
        :A01;
        note left
            Code der Schaltzeitdefinition wird nicht verwendet
        endnote
        kill;
    endif
    if (<b>40: </b> Wurde die ausgerollte Schaltzeitdefinition an den Anfragenden versendet?) then (ja)
        :A02;
        note left
            Ausgerollte Schaltzeitdefinition wurde versendet
            Hinweis: Es ist als Referenz der Geschäftsvorfall zu benennen, mit welchem die ausgerollte Schaltzeitdefinition übermittelt wurde.
        endnote
        kill;
    else (nein)
    endif
    if (<b>200: </b> Ist ein zuvor nicht spezifizierter Fehler aufgetreten?) then (ja)
        :A99;
        note left
            Sonstiges
            Hinweis: Das identifizierte Problem ist in der Antwort zu beschreiben/benennen.
            Nutzungsmöglichkeit Ende: 01.04.2025 00:00 Uhr
        endnote
        kill;
    else (nein)
        :Korrektur der Definition und die erneute Übermittlung durchführen.;
        kill;
    endif
else (nein)
    if (<b>50: </b> Reklamiert der Anfragende eine unplausible ausgerollte Schaltzeitdefinition?) then (ja)
        if (<b>60: </b> Wurde mit dem Code der Schaltzeitdefinition bereits eine ausgerollte Schaltzeitdefinition mit einer höheren Version versendet?) then (ja)
            :A03;
            note left
                Es wurde bereits eine ausgerollte Schaltzeitdefinition für den Code der Schaltzeitdefinition mit einer höheren Version versendet
                Hinweis: Es ist als Referenz der Geschäftsvorfall zu benennen, mit welchem die ausgerollte Schaltzeitdefinition übermittelt wurde.
            endnote
            kill;
        else (nein)
        endif
        if (<b>70: </b> Ist die versendete ausgerollte Schaltzeitdefinition plausibel?) then (ja)
            :A04;
            note left
                Ausgerollte Schaltzeitdefinition ist plausibel
            endnote
            kill;
        else (nein)
        endif
        if (<b>200: </b> Ist ein zuvor nicht spezifizierter Fehler aufgetreten?) then (ja)
            :A99;
            note left
                Sonstiges
                Hinweis: Das identifizierte Problem ist in der Antwort zu beschreiben/benennen.
                Nutzungsmöglichkeit Ende: 01.04.2025 00:00 Uhr
            endnote
            kill;
        else (nein)
            :Korrektur der Definition und die erneute Übermittlung durchführen.;
            kill;
        endif
    else (nein)
        if (<b>100: </b> Reklamiert der Anfragende das Fehlen der ausgerollten Leistungskurvendefinition?) then (ja)
            if (<b>120: </b> Entspricht der Code der Leistungskurvendefinition einem Code aus der für den reklamierten Zeitraum gültigen Übersicht der Leistungskurvendefinition?) then (ja)
            else (nein)
                :A05;
                note left
                    Code der Leistungskurvendefinition wird nicht verwendet
                endnote
                kill;
            endif
            if (<b>130: </b> Wurde die ausgerollte Leistungskurvendefinition an den Anfragenden versendet?) then (ja)
                :A06;
                note left
                    Ausgerollte Leistungskurvendefinition wurde versendet
                    Hinweis: Es ist als Referenz der Geschäftsvorfall zu benennen, mit welchem die ausgerollte Leistungskurvendefinition übermittelt wurde.
                endnote
                kill;
            else (nein)
            endif
            if (<b>200: </b> Ist ein zuvor nicht spezifizierter Fehler aufgetreten?) then (ja)
                :A99;
                note left
                    Sonstiges
                    Hinweis: Das identifizierte Problem ist in der Antwort zu beschreiben/benennen.
                    Nutzungsmöglichkeit Ende: 01.04.2025 00:00 Uhr
                endnote
                kill;
            else (nein)
                :Korrektur der Definition und die erneute Übermittlung durchführen.;
                kill;
            endif
        else (nein)
            if (<b>140: </b> Reklamiert der Anfragende eine unplausible ausgerollte Leistungskurvendefinition?) then (ja)
                if (<b>150: </b> Wurde mit dem Code der Leistungskurvendefinition bereits eine ausgerollte Leistungskurvendefinition mit einer höheren Version versendet?) then (ja)
                    :A07;
                    note left
                        Es wurde bereits eine ausgerollte Leistungskurvendefinition für den Code der Leistungskurvendefinition mit einer höheren Version versendet
                        Hinweis: Es ist als Referenz der Geschäftsvorfall zu benennen, mit welchem die ausgerollte Leistungskurvendefinition übermittelt wurde.
                    endnote
                    kill;
                else (nein)
                endif
                if (<b>160: </b> Ist die versendete ausgerollte Leistungskurvendefinition plausibel?) then (ja)
                    :A08;
                    note left
                        Ausgerollte Leistungskurvendefinition ist plausibel
                    endnote
                    kill;
                else (nein)
                endif
                if (<b>200: </b> Ist ein zuvor nicht spezifizierter Fehler aufgetreten?) then (ja)
                    :A99;
                    note left
                        Sonstiges
                        Hinweis: Das identifizierte Problem ist in der Antwort zu beschreiben/benennen.
                        Nutzungsmöglichkeit Ende: 01.04.2025 00:00 Uhr
                    endnote
                    kill;
                else (nein)
                    :Korrektur der Definition und die erneute Übermittlung durchführen.;
                    kill;
                endif
            else (nein)
            endif
        endif
    endif
endif
if (<b>200: </b> Ist ein zuvor nicht spezifizierter Fehler aufgetreten?) then (ja)
    :A99;
    note left
        Sonstiges
        Hinweis: Das identifizierte Problem ist in der Antwort zu beschreiben/benennen.
        Nutzungsmöglichkeit Ende: 01.04.2025 00:00 Uhr
    endnote
    kill;
else (nein)
    :Korrektur der Definition und die erneute Übermittlung durchführen.;
    kill;
endif

@enduml
