@startuml
skinparam Shadowing false
skinparam NoteBorderColor #f3f1f6
skinparam NoteBackgroundColor #f3f1f6
skinparam NoteFontSize 12
skinparam ActivityBorderColor none
skinparam ActivityBackgroundColor #7a8da1
skinparam ActivityFontSize 16
skinparam ArrowColor #7aab8a
skinparam ArrowFontSize 16
skinparam ActivityDiamondBackgroundColor #7aab8a
skinparam ActivityDiamondBorderColor #7aab8a
skinparam ActivityDiamondFontSize 18
skinparam defaultFontName DejaVu Serif Condensed
skinparam ActivityEndColor #669580

header
<b>FV2210
2022-12-12
endheader

footer
v4.2 | 11.12.2025 (urspr. 01.10.2025)
endfooter

title
MaBiS

7.35.2: AD: Übermittlung Datenstatus für die Bilanzkreissummenzeitreihe vom BIKO an NB und BKV



end title
:<b>E_0057</b>;
note right
<b><i>Prüfende Rolle: BIKO
end note

if (<b>1: </b> Erfolgt der Eingang der Zeitreihe vor Ablauf der Frist für den Erstaufschlag?) then (ja)
    :A01;
    note left
        Datenstatus „Abrechnungsdaten“
    endnote
    kill;
else (nein)
    :A02;
    note left
        Datenstatus „Prüfdaten“
    endnote
    kill;
endif

@enduml
