@startuml
skinparam Shadowing false
skinparam NoteBorderColor #f3f1f6
skinparam NoteBackgroundColor #f3f1f6
skinparam NoteFontSize 12
skinparam ActivityBorderColor none
skinparam ActivityBackgroundColor #7a8da1
skinparam ActivityFontSize 16
skinparam ArrowColor #7aab8a
skinparam ArrowFontSize 16
skinparam ActivityDiamondBackgroundColor #7aab8a
skinparam ActivityDiamondBorderColor #7aab8a
skinparam ActivityDiamondFontSize 18
skinparam defaultFontName DejaVu Serif Condensed
skinparam ActivityEndColor #669580

header
<b>FV2210
2022-12-12
endheader

footer
v4.2 | 11.12.2025 (urspr. 01.10.2025) | ebdamame v1.0.0 | rebdhuhn v1.0.1
endfooter

title
MaBiS

7.51.3: AD: Übermittlung Datenstatus des Deltazeitreihenübertrags vom BIKO an ÜNB und NB



end title
:<b>E_0061</b>;
note right
<b><i>Prüfende Rolle: BIKO
end note

if (<b>1: </b> Ist die eingegangene Prüfmitteilung positiv?) then (ja)
else (nein)
    :A**;
    note left
        Hinweis: A** wird durch richtigen Code aus dem System des BIKO ersetzt. Mögliche Codes sind:
        A01	Datenstatus „Abrechnungsdaten“
        A02	Datenstatus „Prüfdaten“
        A04	Datenstatus „Abrechnungsdaten KBKA“
    endnote
    kill;
endif
if (<b>2: </b> Liegt der Datenstatus „Prüfdaten“ vor?) then (ja)
else (nein)
    :A**;
    note left
        Hinweis: A** wird durch richtigen Code aus dem System des BIKO ersetzt. Mögliche Codes sind:
        A01	Datenstatus „Abrechnungsdaten“
        A04	Datenstatus „Abrechnungsdaten KBKA“
    endnote
    kill;
endif
if (<b>3: </b> Erfolgt der Eingang der Prüfmitteilung innerhalb der Clearingphase für DZÜ der BKA (ohne KBKA&#41;?) then (ja)
    :A01;
    note left
        Datenstatus „Abrechnungsdaten“
    endnote
    kill;
else (nein)
    :A04;
    note left
        Datenstatus „Abrechnungsdaten KBKA“
    endnote
    kill;
endif

@enduml
