@startuml
skinparam Shadowing false
skinparam NoteBorderColor #f3f1f6
skinparam NoteBackgroundColor #f3f1f6
skinparam NoteFontSize 12
skinparam ActivityBorderColor none
skinparam ActivityBackgroundColor #7a8da1
skinparam ActivityFontSize 16
skinparam ArrowColor #7aab8a
skinparam ArrowFontSize 16
skinparam ActivityDiamondBackgroundColor #7aab8a
skinparam ActivityDiamondBorderColor #7aab8a
skinparam ActivityDiamondFontSize 18
skinparam defaultFontName DejaVu Serif Condensed
skinparam ActivityEndColor #669580

header
<b>FV2210
2022-12-12
endheader

title
WiM Strom

8.20.1: AD: Anforderung Wert vom MSB der Marktlokation



end title
:<b>E_0225</b>;
note right
<b><i>Prüfende Rolle: MSB
end note

if (<b>1: </b> Wird die Übermittlung von Werten an die Marktrolle ESA grundsätzlich angeboten?) then (ja)
else (nein)
    :A01;
    note left
        Cluster: Ablehnung
        Der MSB bietet keine freiwillige Übermittlung von Werten an die Marktrolle ESA an.
    endnote
    kill;
endif
if (<b>2: </b> Wird das vom ESA gewünschte Messprodukt entsprechend der Codeliste der Messprodukte angeboten?) then (ja)
else (nein)
    :A02;
    note left
        Cluster: Ablehnung
        Das vom ESA gewünschte Messprodukt wird vom MSB nicht angeboten.
    endnote
    kill;
endif
if (<b>3: </b> Liegt die vertragliche Grundlage zur Anfrage und Übermittlung der Werte und Abrechnung der erbrachten Dienstleistung vom MSB an den ESA beim MSB vor?) then (ja)
else (nein)
    :A03;
    note left
        Cluster: Ablehnung
        Vertragliche Grundlage des ESA liegt nicht vor.
    endnote
    kill;
endif
if (<b>4: </b> Liegt dem MSB eine gültige datenschutzrechtliche Einwilligung (wie z. B. das BDEW-Muster „Einwilligungserklärung in die Verarbeitung personenbezogener Daten nach DS-GVO - 
Anfrage und Übermittlung von Messprodukten 
gemäß BNetzA-Festlegung BK6-20-160“&#41; zur Anfrage und Übermittlung von Messprodukten vor?) then (ja)
else (nein)
    :A04;
    note left
        Cluster: Ablehnung
        Die unterzeichnete Einwilligung für die Lokation liegt nicht vor.
    endnote
    kill;
endif
if (<b>5: </b> Sind die Daten in der Einwilligung plausibel und vollständig?) then (ja)
else (nein)
    :A05;
    note left
        Cluster: Ablehnung
        Vorliegende Einwilligung ist nicht plausibel oder vollständig.
    endnote
    kill;
endif
if (<b>6: </b> Ermöglicht die vorhandene Gerätetechnik die Übermittlung der angefragten Werte entsprechend dem Messprodukt?) then (ja)
else (nein)
    :A06;
    note left
        Cluster: Ablehnung
        Die Gerätetechnik misst die angeforderten Messwerte nicht.
    endnote
    kill;
endif
if (<b>7: </b> Handelt es sich um eine Anfrage von Werten auf Ebene der Marktlokation / Netzlokation?) then (ja)
    if (<b>8: </b> Ist der MSB an allen der Marktlokation / Netzlokation zugeordneten Messlokationen auch der MSB der Messlokation(en&#41;?) then (ja)
    else (nein)
        :A07;
        note left
            Cluster: Ablehnung
            Der MSB der Marktlokation / Netzlokation ist nicht zeitgleich der allen Messlokation(en&#41; zugeordnete MSB.
        endnote
        kill;
    endif
else (nein)
endif
end

@enduml
