@startuml
skinparam Shadowing false
skinparam NoteBorderColor #f3f1f6
skinparam NoteBackgroundColor #f3f1f6
skinparam NoteFontSize 12
skinparam ActivityBorderColor none
skinparam ActivityBackgroundColor #7a8da1
skinparam ActivityFontSize 16
skinparam ArrowColor #7aab8a
skinparam ArrowFontSize 16
skinparam ActivityDiamondBackgroundColor #7aab8a
skinparam ActivityDiamondBorderColor #7aab8a
skinparam ActivityDiamondFontSize 18
skinparam defaultFontName DejaVu Serif Condensed
skinparam ActivityEndColor #669580

header
<b>FV2210
2022-12-12
endheader

title
GPKE

6.26.1: AD: Geschäftsdatenanfrage von LF



end title
:<b>E_0441</b>;
note right
<b><i>Prüfende Rolle: NB
end note

if (<b>1: </b> Ist der LF im angefragten Zeitraum der genannten Marktlokation, Messlokation bzw. Tranche zugeordnet?) then (ja)
else (nein)
    if (<b>2: </b> Ist der LF für den angefragten Zeitraum z. B. aufgrund einer Vollmacht berechtigt die angefragten Stammdaten zu erhalten?) then (ja)
    else (nein)
        :A01;
        note left
            Keine Berechtigung
        endnote
        kill;
    endif
endif
:Stammdaten versenden;
kill;

@enduml
