@startuml
skinparam Shadowing false
skinparam NoteBorderColor #f3f1f6
skinparam NoteBackgroundColor #f3f1f6
skinparam NoteFontSize 12
skinparam ActivityBorderColor none
skinparam ActivityBackgroundColor #7a8da1
skinparam ActivityFontSize 16
skinparam ArrowColor #7aab8a
skinparam ArrowFontSize 16
skinparam ActivityDiamondBackgroundColor #7aab8a
skinparam ActivityDiamondBorderColor #7aab8a
skinparam ActivityDiamondFontSize 18
skinparam defaultFontName DejaVu Serif Condensed
skinparam ActivityEndColor #669580

header
<b>FV2210
2022-12-12
endheader

title
GPKE

6.7.3: AD: Lieferbeginn



end title
:<b>E_0624</b>;
note right
<b><i>Prüfende Rolle: LF
end note

if (<b>5: </b> Ist die Anfrage ausgehend vom ÜT der Lieferanmeldung bis 07:00 Uhr des nächsten Werktages eingegangen?) then (ja)
else (nein)
    :A43;
    note left
        Cluster: Ablehnung
        Fristüberschreitung
    endnote
    kill;
endif
if (<b>10: </b> Wurde der Anwendungsfall für eine verbrauchende Marktlokation verwendet?) then (ja)
    if (<b>20: </b> Besteht zum Folgetag des in der Anfrage zur Beendigung der Zuordnung genannten Termins eine Zuordnung für diese Marktlokation?
Hinweis: Ist der Kunde in der E/G, ist diese Frage ebenfalls mit ja zu beantworten) then (ja)
        if (<b>40: </b> Liegt in der Anfrage zur Beendigung der Zuordnung der Transaktionsgrund Ein-/ Auszug (Umzug&#41; vor?) then (ja)
            if (<b>50: </b> Ist der Kunde aus der Anfrage zur Beendigung der Zuordnung identisch mit dem Kunden beim LFA?) then (ja)
                :A32;
                note left
                    Cluster: Ablehnung
                    Es handelt sich nicht um einen Einzug, da der Kunde aus der Anfrage zur Beendigung der Zuordnung identisch mit dem Kunden beim LFA ist.
                endnote
                kill;
            else (nein)
            endif
            if (<b>60: </b> Hat der LFA Informationen darüber, dass sein Kunde nicht ausgezogen ist?) then (ja)
                :A33;
                note left
                    Cluster: Ablehnung
                    Der LFA hat die Information, dass der Kunde nicht ausgezogen ist.
                endnote
                kill;
            else (nein)
                :A34;
                note left
                    Cluster: Zustimmung 
                    Der LFA beendet die Belieferung und teilt sein Lieferendedatum in der Antwort mit.
                endnote
                kill;
            endif
        else (nein)
            if (<b>70: </b> Ist der LFA ein Lieferant der auch Grundversorger ist?) then (ja)
                if (<b>80: </b> Befindet sich die Marktlokation zum Folgetag des Enddatums aus der Anfrage zur Beendigung der Zuordnung in der Ersatz-versorgung?) then (ja)
                    :A38;
                    note left
                        Cluster: Zustimmung
                        Ersatzversorgung wurde zum angefragten Termin beendet.
                    endnote
                    kill;
                else (nein)
                endif
                if (<b>90: </b> Bleibt das Vertragsverhältnis des LFA mit dem Kunden an dieser Marktlokation / Tranchen zum Tag nach dem Enddatum aus der Anfrage zur Beendigung der Zuordnung bestehen?) then (ja)
                    :A35;
                    note left
                        Cluster: Ablehnung
                        Es besteht eine Vertragsbindung
                    endnote
                    kill;
                else (nein)
                    :A36;
                    note left
                        Cluster: Zustimmung
                        Vertragsverhältnis wurde zum angefragten oder davor liegenden Termin beendet.
                    endnote
                    kill;
                endif
            else (nein)
            endif
            if (<b>90: </b> Bleibt das Vertragsverhältnis des LFA mit dem Kunden an dieser Marktlokation / Tranchen zum Tag nach dem Enddatum aus der Anfrage zur Beendigung der Zuordnung bestehen?) then (ja)
                :A35;
                note left
                    Cluster: Ablehnung
                    Es besteht eine Vertragsbindung
                endnote
                kill;
            else (nein)
                :A36;
                note left
                    Cluster: Zustimmung
                    Vertragsverhältnis wurde zum angefragten oder davor liegenden Termin beendet.
                endnote
                kill;
            endif
        endif
    else (nein)
        if (<b>30: </b> Liegt dem LFA bereits eine bestätigtes Zuordnungsende vor?) then (ja)
            :A30;
            note left
                Cluster: Ablehnung
                Die Belieferung wurde zu dem angefragten Ter-min aus der Anfrage zur Beendigung der Zuordnung bereits beendet und eine Abmeldung von dem LFA bereits versendet, die durch den NB bereits bestätigt wurde.
            endnote
            kill;
        else (nein)
            :A31;
            note left
                Cluster: Zustimmung
                Zustimmung der Anfrage zur Beendigung der Zuordnung zum in der bereits versendeten Abmeldung (welche noch nicht beantwortet wurde&#41; genannten Termin.
            endnote
            kill;
        endif
    endif
else (nein)
    if (<b>200: </b> Besteht zum Folgetag des in der Anfrage zur Beendigung der Zuordnung genannten Termins eine Zuordnung für diese Marktlokation / Tranche?) then (ja)
        if (<b>220: </b> Bleibt das Vertragsverhältnis des LFA mit dem Kunden an dieser Marktlokation / Tranche zum Tag nach dem Enddatum aus der Anfrage zur Beendigung der Zuordnung bestehen?) then (ja)
            :A39;
            note left
                Cluster: Ablehnung
                Es besteht eine Vertragsbindung
            endnote
            kill;
        else (nein)
            :A40;
            note left
                Cluster: Zustimmung
                Vertragsverhältnis wurde zum angefragten oder davor liegenden Termin beendet.
            endnote
            kill;
        endif
    else (nein)
        if (<b>210: </b> Liegt dem LFA bereits eine bestätigtes Zuordnungsende vor?) then (ja)
            :A41;
            note left
                Cluster: Ablehnung
                Die Belieferung wurde zu dem angefragten Ter-min aus der Anfrage zur Beendigung der Zuordnung bereits beendet und eine Abmeldung von dem LFA bereits versendet, die durch den NB bereits bestätigt wurde.
            endnote
            kill;
        else (nein)
            :A42;
            note left
                Cluster: Zustimmung
                Zustimmung der Anfrage zur Beendigung der Zuordnung zum in der bereits versendeten Abmeldung (welche noch nicht beantwortet wurde&#41; genannten Termin.
            endnote
            kill;
        endif
    endif
endif

@enduml
