@startuml
skinparam Shadowing false
skinparam NoteBorderColor #f3f1f6
skinparam NoteBackgroundColor #f3f1f6
skinparam NoteFontSize 12
skinparam ActivityBorderColor none
skinparam ActivityBackgroundColor #7a8da1
skinparam ActivityFontSize 16
skinparam ArrowColor #7aab8a
skinparam ArrowFontSize 16
skinparam ActivityDiamondBackgroundColor #7aab8a
skinparam ActivityDiamondBorderColor #7aab8a
skinparam ActivityDiamondFontSize 18
skinparam defaultFontName DejaVu Serif Condensed
skinparam ActivityEndColor #669580

header
<b>FV2210
2022-12-12
endheader

title
Dummy Chapter

Dummy Subchapter



end title
:<b>E_0067</b>;
note right
<b><i>Prüfende Rolle: BIKO
end note

if (<b>1: </b> Erfolgt der Eingang der Zeitreihe vor Ablauf der Frist für die Clearingphase BKA (ohne KBKA&#41;?) then (ja)
    :A01;
    note left
        Datenstatus „Abrechnungsdaten“
    endnote
    kill;
else (nein)
    :A04;
    note left
        Datenstatus „Abrechnungsdaten KBKA“
    endnote
    kill;
endif

@enduml
