@startuml
skinparam Shadowing false
skinparam NoteBorderColor #f3f1f6
skinparam NoteBackgroundColor #f3f1f6
skinparam NoteFontSize 12
skinparam ActivityBorderColor none
skinparam ActivityBackgroundColor #7a8da1
skinparam ActivityFontSize 16
skinparam ArrowColor #7aab8a
skinparam ArrowFontSize 16
skinparam ActivityDiamondBackgroundColor #7aab8a
skinparam ActivityDiamondBorderColor #7aab8a
skinparam ActivityDiamondFontSize 18
skinparam defaultFontName DejaVu Serif Condensed
skinparam ActivityEndColor #669580

header
<b>FV2210
2022-12-12
endheader

title
GPKE

6.1.1: AD: Kündigung



end title
:<b>E_0400</b>;
note right
<b><i>Prüfende Rolle: LF
end note

if (<b>1: </b> Liegt der übermittelte Kündigungstermin vor dem Nachrichteneingang?) then (ja)
    :A12;
    note left
        Cluster: Ablehnung
        Fristüberschreitung
    endnote
    kill;
else (nein)
endif
if (<b>2: </b> Ist in der Kündigung die Angabe der Identifikationslogik mit dem Wert „Marktlokations-ID“ angegeben?) then (ja)
    if (<b>3: </b> Wurde mit der in der Kündigung angegebenen ID der Marktlokation im IT-System des Empfängers eine Marktlokation identifiziert, welcher der Empfänger für mindestens einen Tag zugeordnet war bzw. ist bzw. sein wird?) then (ja)
    else (nein)
        :A01;
        note left
            Cluster: Ablehnung
            Die Marktlokation ist nicht identifizierbar.
        endnote
        kill;
    endif
    if (<b>9: </b> Liegt der in der Kündigung angefragte Termin vor dem Beginn des Vertrages zwischen dem Kunden und dem Empfänger?) then (ja)
        :A13;
        note left
            Cluster: Ablehnung
            Empfänger ist zum angefragten Zeitpunkt nicht zugeordnet.
        endnote
        kill;
    else (nein)
    endif
    if (<b>10: </b> Wurde der Vertrag bereits zu dem angefragten Kündigungstermin gekündigt?) then (ja)
        :A06;
        note left
            Cluster: Zustimmung
            Vertrag wurde bereits zum angefragten Kündigungstermin gekündigt.
        endnote
        kill;
    else (nein)
    endif
    if (<b>11: </b> Wurde der Vertrag bereits zu einem Datum vor dem angefragten Kündigungstermin gekündigt?) then (ja)
        :A07;
        note left
            Cluster: Ablehnung
            Zum Kündigungstermin besteht kein Vertrags-verhältnis mehr.
        endnote
        kill;
    else (nein)
    endif
    if (<b>12: </b> Handelt es sich um eine Kündigung, welche zu einem fixen Termin ausgesprochen wurde?) then (ja)
        if (<b>13: </b> Ist der Vertrag zum übermittelten Kündigungstermin unter Einhaltung der Kündigungsfrist unter Berücksichtigung des Eingangsdatums der Kündigung kündbar?) then (ja)
        else (nein)
            if (<b>14: </b> Wurde der Vertrag bereits zu einem späteren Zeitpunkt beendet?) then (ja)
                :A08;
                note left
                    Cluster: Ablehnung
                    Vertragsbindung bei bereits in der Zukunft beendetem Vertrag.
                endnote
                kill;
            else (nein)
                :A09;
                note left
                    Cluster: Ablehnung
                    Vertragsbindung
                endnote
                kill;
            endif
        endif
    else (nein)
    endif
    :A11;
    note left
        Cluster: Zustimmung
        Zustimmung
    endnote
    kill;
else (nein)
    if (<b>4: </b> Wurde mit allen zur Verfügung gestellten Informationen in der Kündigung ohne Berücksichtigung des Kundennamens unter Wahrung der gebotenen Sorgfalt genau eine Marktlokation ermittelt?) then (ja)
        if (<b>5: </b> Entspricht der Kunde aus der Kündigung dem Vertragspartner beim Empfänger der Kündigung? (Identifizierung unter Wahrung der gebotenen Sorgfalt&#41;) then (ja)
        else (nein)
            :A02;
            note left
                Cluster: Ablehnung
                Angefragter Kunde ist nicht der Vertragspartner beim LFA.
            endnote
            kill;
        endif
        if (<b>8: </b> Handelt es sich bei dem identifizierten Objekt um einen Teil einer Kundenanlage, welches zum Kündigungsdatum + 1 Tag nicht an der Marktkommunikation teilnimmt? 
(Teil einer Kundenanlage, welche dem NB nicht bekannt ist.&#41;) then (ja)
            :A05;
            note left
                Cluster: Ablehnung
                Teil einer Kundenanlage, die derzeit nicht se-parat bilanziert wird.
            endnote
            kill;
        else (nein)
        endif
        if (<b>9: </b> Liegt der in der Kündigung angefragte Termin vor dem Beginn des Vertrages zwischen dem Kunden und dem Empfänger?) then (ja)
            :A13;
            note left
                Cluster: Ablehnung
                Empfänger ist zum angefragten Zeitpunkt nicht zugeordnet.
            endnote
            kill;
        else (nein)
        endif
        if (<b>10: </b> Wurde der Vertrag bereits zu dem angefragten Kündigungstermin gekündigt?) then (ja)
            :A06;
            note left
                Cluster: Zustimmung
                Vertrag wurde bereits zum angefragten Kündigungstermin gekündigt.
            endnote
            kill;
        else (nein)
        endif
        if (<b>11: </b> Wurde der Vertrag bereits zu einem Datum vor dem angefragten Kündigungstermin gekündigt?) then (ja)
            :A07;
            note left
                Cluster: Ablehnung
                Zum Kündigungstermin besteht kein Vertrags-verhältnis mehr.
            endnote
            kill;
        else (nein)
        endif
        if (<b>12: </b> Handelt es sich um eine Kündigung, welche zu einem fixen Termin ausgesprochen wurde?) then (ja)
            if (<b>13: </b> Ist der Vertrag zum übermittelten Kündigungstermin unter Einhaltung der Kündigungsfrist unter Berücksichtigung des Eingangsdatums der Kündigung kündbar?) then (ja)
            else (nein)
                if (<b>14: </b> Wurde der Vertrag bereits zu einem späteren Zeitpunkt beendet?) then (ja)
                    :A08;
                    note left
                        Cluster: Ablehnung
                        Vertragsbindung bei bereits in der Zukunft beendetem Vertrag.
                    endnote
                    kill;
                else (nein)
                    :A09;
                    note left
                        Cluster: Ablehnung
                        Vertragsbindung
                    endnote
                    kill;
                endif
            endif
        else (nein)
        endif
        :A11;
        note left
            Cluster: Zustimmung
            Zustimmung
        endnote
        kill;
    else (nein)
        if (<b>6: </b> Wurde mit den zur Verfügung gestellten Informationen in der Kündigung mehr als eine Marktlokation ermittelt?) then (ja)
        else (nein)
            :A03;
            note left
                Cluster: Ablehnung
                Keine Identifizierung einer Marktlokation.
            endnote
            kill;
        endif
        if (<b>7: </b> Entspricht der Kunde aus der Kündigung bei exakt einer Marktlokation, dem Vertragspartner beim Empfänger der Kündigung, mit welchem der LFA zum Kündigungsdatum einen Vertrag hat? 
(Identifizierung unter Wahrung der gebotenen Sorgfalt&#41;) then (ja)
        else (nein)
            :A04;
            note left
                Cluster: Ablehnung
                Mehrere Marktlokationen wurden identifiziert, Kunde war bei keiner bzw. mehreren Marktlokationen zugeordnet.
            endnote
            kill;
        endif
        if (<b>8: </b> Handelt es sich bei dem identifizierten Objekt um einen Teil einer Kundenanlage, welches zum Kündigungsdatum + 1 Tag nicht an der Marktkommunikation teilnimmt? 
(Teil einer Kundenanlage, welche dem NB nicht bekannt ist.&#41;) then (ja)
            :A05;
            note left
                Cluster: Ablehnung
                Teil einer Kundenanlage, die derzeit nicht se-parat bilanziert wird.
            endnote
            kill;
        else (nein)
        endif
        if (<b>9: </b> Liegt der in der Kündigung angefragte Termin vor dem Beginn des Vertrages zwischen dem Kunden und dem Empfänger?) then (ja)
            :A13;
            note left
                Cluster: Ablehnung
                Empfänger ist zum angefragten Zeitpunkt nicht zugeordnet.
            endnote
            kill;
        else (nein)
        endif
        if (<b>10: </b> Wurde der Vertrag bereits zu dem angefragten Kündigungstermin gekündigt?) then (ja)
            :A06;
            note left
                Cluster: Zustimmung
                Vertrag wurde bereits zum angefragten Kündigungstermin gekündigt.
            endnote
            kill;
        else (nein)
        endif
        if (<b>11: </b> Wurde der Vertrag bereits zu einem Datum vor dem angefragten Kündigungstermin gekündigt?) then (ja)
            :A07;
            note left
                Cluster: Ablehnung
                Zum Kündigungstermin besteht kein Vertrags-verhältnis mehr.
            endnote
            kill;
        else (nein)
        endif
        if (<b>12: </b> Handelt es sich um eine Kündigung, welche zu einem fixen Termin ausgesprochen wurde?) then (ja)
            if (<b>13: </b> Ist der Vertrag zum übermittelten Kündigungstermin unter Einhaltung der Kündigungsfrist unter Berücksichtigung des Eingangsdatums der Kündigung kündbar?) then (ja)
            else (nein)
                if (<b>14: </b> Wurde der Vertrag bereits zu einem späteren Zeitpunkt beendet?) then (ja)
                    :A08;
                    note left
                        Cluster: Ablehnung
                        Vertragsbindung bei bereits in der Zukunft beendetem Vertrag.
                    endnote
                    kill;
                else (nein)
                    :A09;
                    note left
                        Cluster: Ablehnung
                        Vertragsbindung
                    endnote
                    kill;
                endif
            endif
        else (nein)
        endif
        :A11;
        note left
            Cluster: Zustimmung
            Zustimmung
        endnote
        kill;
    endif
    if (<b>8: </b> Handelt es sich bei dem identifizierten Objekt um einen Teil einer Kundenanlage, welches zum Kündigungsdatum + 1 Tag nicht an der Marktkommunikation teilnimmt? 
(Teil einer Kundenanlage, welche dem NB nicht bekannt ist.&#41;) then (ja)
        :A05;
        note left
            Cluster: Ablehnung
            Teil einer Kundenanlage, die derzeit nicht se-parat bilanziert wird.
        endnote
        kill;
    else (nein)
    endif
    if (<b>9: </b> Liegt der in der Kündigung angefragte Termin vor dem Beginn des Vertrages zwischen dem Kunden und dem Empfänger?) then (ja)
        :A13;
        note left
            Cluster: Ablehnung
            Empfänger ist zum angefragten Zeitpunkt nicht zugeordnet.
        endnote
        kill;
    else (nein)
    endif
    if (<b>10: </b> Wurde der Vertrag bereits zu dem angefragten Kündigungstermin gekündigt?) then (ja)
        :A06;
        note left
            Cluster: Zustimmung
            Vertrag wurde bereits zum angefragten Kündigungstermin gekündigt.
        endnote
        kill;
    else (nein)
    endif
    if (<b>11: </b> Wurde der Vertrag bereits zu einem Datum vor dem angefragten Kündigungstermin gekündigt?) then (ja)
        :A07;
        note left
            Cluster: Ablehnung
            Zum Kündigungstermin besteht kein Vertrags-verhältnis mehr.
        endnote
        kill;
    else (nein)
    endif
    if (<b>12: </b> Handelt es sich um eine Kündigung, welche zu einem fixen Termin ausgesprochen wurde?) then (ja)
        if (<b>13: </b> Ist der Vertrag zum übermittelten Kündigungstermin unter Einhaltung der Kündigungsfrist unter Berücksichtigung des Eingangsdatums der Kündigung kündbar?) then (ja)
        else (nein)
            if (<b>14: </b> Wurde der Vertrag bereits zu einem späteren Zeitpunkt beendet?) then (ja)
                :A08;
                note left
                    Cluster: Ablehnung
                    Vertragsbindung bei bereits in der Zukunft beendetem Vertrag.
                endnote
                kill;
            else (nein)
                :A09;
                note left
                    Cluster: Ablehnung
                    Vertragsbindung
                endnote
                kill;
            endif
        endif
    else (nein)
    endif
    :A11;
    note left
        Cluster: Zustimmung
        Zustimmung
    endnote
    kill;
endif
if (<b>9: </b> Liegt der in der Kündigung angefragte Termin vor dem Beginn des Vertrages zwischen dem Kunden und dem Empfänger?) then (ja)
    :A13;
    note left
        Cluster: Ablehnung
        Empfänger ist zum angefragten Zeitpunkt nicht zugeordnet.
    endnote
    kill;
else (nein)
endif
if (<b>10: </b> Wurde der Vertrag bereits zu dem angefragten Kündigungstermin gekündigt?) then (ja)
    :A06;
    note left
        Cluster: Zustimmung
        Vertrag wurde bereits zum angefragten Kündigungstermin gekündigt.
    endnote
    kill;
else (nein)
endif
if (<b>11: </b> Wurde der Vertrag bereits zu einem Datum vor dem angefragten Kündigungstermin gekündigt?) then (ja)
    :A07;
    note left
        Cluster: Ablehnung
        Zum Kündigungstermin besteht kein Vertrags-verhältnis mehr.
    endnote
    kill;
else (nein)
endif
if (<b>12: </b> Handelt es sich um eine Kündigung, welche zu einem fixen Termin ausgesprochen wurde?) then (ja)
    if (<b>13: </b> Ist der Vertrag zum übermittelten Kündigungstermin unter Einhaltung der Kündigungsfrist unter Berücksichtigung des Eingangsdatums der Kündigung kündbar?) then (ja)
    else (nein)
        if (<b>14: </b> Wurde der Vertrag bereits zu einem späteren Zeitpunkt beendet?) then (ja)
            :A08;
            note left
                Cluster: Ablehnung
                Vertragsbindung bei bereits in der Zukunft beendetem Vertrag.
            endnote
            kill;
        else (nein)
            :A09;
            note left
                Cluster: Ablehnung
                Vertragsbindung
            endnote
            kill;
        endif
    endif
else (nein)
endif
:A11;
note left
    Cluster: Zustimmung
    Zustimmung
endnote
kill;

@enduml
