@startuml
skinparam Shadowing false
skinparam NoteBorderColor #f3f1f6
skinparam NoteBackgroundColor #f3f1f6
skinparam NoteFontSize 12
skinparam ActivityBorderColor none
skinparam ActivityBackgroundColor #7a8da1
skinparam ActivityFontSize 16
skinparam ArrowColor #7aab8a
skinparam ArrowFontSize 16
skinparam ActivityDiamondBackgroundColor #7aab8a
skinparam ActivityDiamondBorderColor #7aab8a
skinparam ActivityDiamondFontSize 18
skinparam defaultFontName DejaVu Serif Condensed
skinparam ActivityEndColor #669580

header
<b>FV2210
2022-12-12
endheader

title
GPKE

6.32.1: AD: Bestellung Änderung Zählzeitdefinition des NB vom LF



end title
:<b>E_0483</b>;
note right
<b><i>Prüfende Rolle: NB
end note

if (<b>1: </b> Handelt es sich bei der Marktlokation um eine verbrauchende Marktlokation?) then (ja)
else (nein)
    :A07;
    note left
        Cluster: Ablehnung 
        Bestellungen sind nur für verbrauchende Marktlokationen möglich
    endnote
    kill;
endif
if (<b>2: </b> Handelt es sich bei der Bestellung um eine Rückkehr auf eine Eintariflogik?) then (ja)
else (nein)
    if (<b>3: </b> Ist die gewünschte Zählzeit zum Anwendungszeitpunkt Bestandteil der Übersicht der Zählzeitdefinition, welche zuvor vom NB übermittelt wurde?) then (ja)
    else (nein)
        :A01;
        note left
            Cluster: Ablehnung 
            Zählzeitdefinition zum Anwendungszeitpunkt nicht bekannt
        endnote
        kill;
    endif
    if (<b>4: </b> Ist die in der Bestellung genannte Zählzeit in der Übersicht der Zählzeitdefinition des NB als eine bestellbare Zählzeit gekennzeichnet?) then (ja)
    else (nein)
        :A06;
        note left
            Cluster: Ablehnung 
            Zählzeit ist nicht bestallbar
        endnote
        kill;
    endif
    if (<b>5: </b> Liegt zum Anwendungszeitpunkt die ausgerollte Zählzeit zur Zählzeitdefinition vor?) then (ja)
    else (nein)
        :A02;
        note left
            Cluster: Ablehnung 
            Ausgerollte Zählzeit zur Zählzeitdefinition liegt zum Anwendungszeitpunkt nicht vor
        endnote
        kill;
    endif
    if (<b>6: </b> Ist der bestellte Zustand bereits vorhanden?) then (ja)
        :A03;
        note left
            Cluster: Ablehnung 
            Bestellter Zustand bereits vorhanden
        endnote
        kill;
    else (nein)
    endif
    if (<b>7: </b> Ist die gewünschte Konfiguration grundsätzlich möglich?) then (ja)
    else (nein)
        :A09;
        note left
            Cluster: Ablehnung 
            Konfiguration technisch nicht möglich
            Hinweis: z. B. Zählzeit bestellt und Eintarifzähler verbaut
        endnote
        kill;
    endif
    if (<b>8: </b> Wurde die Vorlauffristen zu der geplanten Änderung der Gerätekonfiguration eingehalten?) then (ja)
    else (nein)
        :A08;
        note left
            Cluster: Ablehnung 
            Fristüberschreitung
        endnote
        kill;
    endif
    if (<b>9: </b> Ist ein zuvor nicht spezifizierter Fehler aufgetreten?) then (ja)
        :A99;
        note left
            Cluster: Ablehnung 
            Sonstiges
            Hinweis: Das identifizierte Problem ist in der Antwort zu beschreiben/benennen.
            Nutzungsmöglichkeit Ende: 01.10.2023 00:00 Uhr
        endnote
        kill;
    else (nein)
        :A04;
        note left
            Cluster: Zustimmung
            Bestellung wird an den MSB der Marktlokation weitergeleitet
        endnote
        kill;
    endif
endif
if (<b>6: </b> Ist der bestellte Zustand bereits vorhanden?) then (ja)
    :A03;
    note left
        Cluster: Ablehnung 
        Bestellter Zustand bereits vorhanden
    endnote
    kill;
else (nein)
endif
if (<b>7: </b> Ist die gewünschte Konfiguration grundsätzlich möglich?) then (ja)
else (nein)
    :A09;
    note left
        Cluster: Ablehnung 
        Konfiguration technisch nicht möglich
        Hinweis: z. B. Zählzeit bestellt und Eintarifzähler verbaut
    endnote
    kill;
endif
if (<b>8: </b> Wurde die Vorlauffristen zu der geplanten Änderung der Gerätekonfiguration eingehalten?) then (ja)
else (nein)
    :A08;
    note left
        Cluster: Ablehnung 
        Fristüberschreitung
    endnote
    kill;
endif
if (<b>9: </b> Ist ein zuvor nicht spezifizierter Fehler aufgetreten?) then (ja)
    :A99;
    note left
        Cluster: Ablehnung 
        Sonstiges
        Hinweis: Das identifizierte Problem ist in der Antwort zu beschreiben/benennen.
        Nutzungsmöglichkeit Ende: 01.10.2023 00:00 Uhr
    endnote
    kill;
else (nein)
    :A04;
    note left
        Cluster: Zustimmung
        Bestellung wird an den MSB der Marktlokation weitergeleitet
    endnote
    kill;
endif

@enduml
