@startuml
skinparam Shadowing false
skinparam NoteBorderColor #f3f1f6
skinparam NoteBackgroundColor #f3f1f6
skinparam NoteFontSize 12
skinparam ActivityBorderColor none
skinparam ActivityBackgroundColor #7a8da1
skinparam ActivityFontSize 16
skinparam ArrowColor #7aab8a
skinparam ArrowFontSize 16
skinparam ActivityDiamondBackgroundColor #7aab8a
skinparam ActivityDiamondBorderColor #7aab8a
skinparam ActivityDiamondFontSize 18
skinparam defaultFontName DejaVu Serif Condensed
skinparam ActivityEndColor #669580

header
<b>FV2210
2022-12-12
endheader

title
Dummy Chapter

Dummy Subchapter



end title
:<b>E_0486</b>;
note right
<b><i>Prüfende Rolle: MSB der Marktlokation
end note

if (<b>1: </b> Handelt es sich bei der Bestellung um eine Abbestellung einer Zählzeit?) then (ja)
    if (<b>2: </b> Ist eine Zählzeit des LF für die genannte Marktlokation zum Ausführungsdatum vorhanden?) then (ja)
    else (nein)
        :A06;
        note left
            Eine Zählzeit des LF ist auf der Marktlokation nicht vorhanden
        endnote
        kill;
    endif
    if (<b>7: </b> Ist ein nicht spezifizierter Fehler aufgetreten?) then (ja)
        :A99;
        note left
            Ablehnung Sonstiges
            Hinweis: Das identifizierte Problem ist in der Antwort zu beschreiben/benennen. Nutzungsmöglichkeit Ende: 01.10.2023 00:00 Uhr
        endnote
        kill;
    else (nein)
        :A05;
        note left
            Bestellung wird an den MSB der Messlokation weitergeleitet
        endnote
        kill;
    endif
else (nein)
    if (<b>3: </b> Handelt es sich um eine Marktlokation mit der messtechnischen Einordnung „iMS“?) then (ja)
    else (nein)
        :A01;
        note left
            Marktlokation befindet sich nicht in der messtechnischen Einordnung „iMS“.
        endnote
        kill;
    endif
    if (<b>4: </b> Ist die gewünschte Zählzeit zum Anwendungszeitpunkt Bestandteil der Übersicht der Zählzeitdefinition, welche zuvor vom LF übermittelt wurde?) then (ja)
    else (nein)
        :A02;
        note left
            Zählzeitdefinition zum Anwendungszeitpunkt nicht bekannt
        endnote
        kill;
    endif
    if (<b>5: </b> Liegt zum Anwendungszeitpunkt die ausgerollte Zählzeit zur Zählzeitdefinition vor?) then (ja)
    else (nein)
        :A03;
        note left
            Ausgerollte Zählzeit zur Zählzeitdefinition liegt zum Anwendungszeitpunkt nicht vor
        endnote
        kill;
    endif
    if (<b>6: </b> Ist der bestellte Zustand bereits vorhanden?) then (ja)
        :A04;
        note left
            Bestellter Zustand bereits vorhanden
        endnote
        kill;
    else (nein)
    endif
    if (<b>7: </b> Ist ein nicht spezifizierter Fehler aufgetreten?) then (ja)
        :A99;
        note left
            Ablehnung Sonstiges
            Hinweis: Das identifizierte Problem ist in der Antwort zu beschreiben/benennen. Nutzungsmöglichkeit Ende: 01.10.2023 00:00 Uhr
        endnote
        kill;
    else (nein)
        :A05;
        note left
            Bestellung wird an den MSB der Messlokation weitergeleitet
        endnote
        kill;
    endif
endif
if (<b>7: </b> Ist ein nicht spezifizierter Fehler aufgetreten?) then (ja)
    :A99;
    note left
        Ablehnung Sonstiges
        Hinweis: Das identifizierte Problem ist in der Antwort zu beschreiben/benennen. Nutzungsmöglichkeit Ende: 01.10.2023 00:00 Uhr
    endnote
    kill;
else (nein)
    :A05;
    note left
        Bestellung wird an den MSB der Messlokation weitergeleitet
    endnote
    kill;
endif

@enduml
