@startuml
skinparam Shadowing false
skinparam NoteBorderColor #f3f1f6
skinparam NoteBackgroundColor #f3f1f6
skinparam NoteFontSize 12
skinparam ActivityBorderColor none
skinparam ActivityBackgroundColor #7a8da1
skinparam ActivityFontSize 16
skinparam ArrowColor #7aab8a
skinparam ArrowFontSize 16
skinparam ActivityDiamondBackgroundColor #7aab8a
skinparam ActivityDiamondBorderColor #7aab8a
skinparam ActivityDiamondFontSize 18
skinparam defaultFontName DejaVu Serif Condensed
skinparam ActivityEndColor #669580

header
<b>FV2210
2022-12-12
endheader

title
MaBiS

7.38.1: AD: Anforderung und Übermittlung Bilanzkreiszuordnungsliste zwischen ÜNB und BKV (Erstabonnierung)



end title
:<b>E_0045</b>;
note right
<b><i>Prüfende Rolle: ÜNB
end note

if (<b>1: </b> Sind in dem angefragten Gebiet (Bilanzierungsgebiet oder Regelzone&#41; für diesen Bilanzkreis LF-SZR zum angegebenen Zeitpunkt gültig?) then (ja)
    end
else (nein)
    :A01;
    note left
        Kein Lieferant zugeordnet
    endnote
    kill;
endif

@enduml
