@startuml
skinparam Shadowing false
skinparam NoteBorderColor #f3f1f6
skinparam NoteBackgroundColor #f3f1f6
skinparam NoteFontSize 12
skinparam ActivityBorderColor none
skinparam ActivityBackgroundColor #7a8da1
skinparam ActivityFontSize 16
skinparam ArrowColor #7aab8a
skinparam ArrowFontSize 16
skinparam ActivityDiamondBackgroundColor #7aab8a
skinparam ActivityDiamondBorderColor #7aab8a
skinparam ActivityDiamondFontSize 18
skinparam defaultFontName DejaVu Serif Condensed
skinparam ActivityEndColor #669580

header
<b>FV2210
2022-12-12
endheader

footer
v4.1 | 11.12.2025 (urspr. 01.04.2025) | ebdamame v1.0.0 | rebdhuhn v1.0.1
endfooter

title
MaBiS

7.26.2: AD: Übermittlung Prüfmitteilung für die Bilanzierungsgebietssummenzeitreihe an ÜNB



end title
:<b>E_0019</b>;
note right
<b><i>Prüfende Rolle: BIKO
end note

if (<b>1: </b> Erfolgt der Eingang der Prüfmitteilung nach Ablauf der Clearingfrist für die KBKA?) then (ja)
    :A01;
    note left
        Fristüberschreitung
    endnote
    kill;
else (nein)
    end
endif

@enduml
