@startuml
skinparam Shadowing false
skinparam NoteBorderColor #f3f1f6
skinparam NoteBackgroundColor #f3f1f6
skinparam NoteFontSize 12
skinparam ActivityBorderColor none
skinparam ActivityBackgroundColor #7a8da1
skinparam ActivityFontSize 16
skinparam ArrowColor #7aab8a
skinparam ArrowFontSize 16
skinparam ActivityDiamondBackgroundColor #7aab8a
skinparam ActivityDiamondBorderColor #7aab8a
skinparam ActivityDiamondFontSize 18
skinparam defaultFontName DejaVu Serif Condensed
skinparam ActivityEndColor #669580

header
<b>FV2210
2022-12-12
endheader

footer
v4.1 | 11.12.2025 (urspr. 01.04.2025) | ebdamame v1.0.0 | rebdhuhn v1.0.1
endfooter

title
WiM Strom

8.12.1: AD: Beendigung der Rechnungsabwicklung des Messstellenbetriebes über den LF durch den LF



end title
:<b>E_0209</b>;
note right
<b><i>Prüfende Rolle: MSB
end note

if (<b>1: </b> Besteht ein Vertragsverhältnis über die Rechnungsabwicklung über den LF?) then (ja)
else (nein)
    :A01;
    note left
        Cluster: Ablehnung
        LF ist nicht Zahler des Messstellenbetriebs
    endnote
    kill;
endif
if (<b>2: </b> Liegt das Beendigungsdatum nach dem Stichtag, der wie folgt berechnet wird: Eingangsdatum der Nachricht - (6 Wochen + 5 WT&#41;?) then (ja)
    :A02;
    note left
        Cluster: Zustimmung
        Zustimmung
    endnote
    kill;
else (nein)
    :A04;
    note left
        Cluster: Ablehnung
        Frist nicht eingehalten
    endnote
    kill;
endif

@enduml
