@startuml
skinparam Shadowing false
skinparam NoteBorderColor #f3f1f6
skinparam NoteBackgroundColor #f3f1f6
skinparam NoteFontSize 12
skinparam ActivityBorderColor none
skinparam ActivityBackgroundColor #7a8da1
skinparam ActivityFontSize 16
skinparam ArrowColor #7aab8a
skinparam ArrowFontSize 16
skinparam ActivityDiamondBackgroundColor #7aab8a
skinparam ActivityDiamondBorderColor #7aab8a
skinparam ActivityDiamondFontSize 18
skinparam defaultFontName DejaVu Serif Condensed
skinparam ActivityEndColor #669580

header
<b>FV2210
2022-12-12
endheader

footer
v4.1 | 11.12.2025 (urspr. 01.04.2025)
endfooter

title
GPKE

6.9.1: AD: Übermittlung des Lieferscheins zur Netznutzungsabrechnung



end title
:<b>E_0456</b>;
note right
<b><i>Prüfende Rolle: LF
end note

if (<b>1: </b> Handelt es sich bei der Marktlokation um eine verbrauchende Marktlokation?) then (ja)
else (nein)
    :A01;
    note left
        Cluster: Ablehnung
        Für diese Marktlokation ist kein Lieferschein zu versenden.
    endnote
    kill;
endif
if (<b>2: </b> Liegt das Endedatum des Zeitraums des Lieferscheins in der Zukunft?) then (ja)
    :A02;
    note left
        Cluster: Ablehnung
        Endedatum liegt in der Zukunft.
    endnote
    kill;
else (nein)
endif
if (<b>3: </b> Entspricht der Typ dieses Lieferscheins (Grund-/Arbeitspreis bzw. Arbeits-/Leistungspreis&#41; für den übermittelten Zeit-raum der an der Marktlokation hinterlegten Netznutzungsabrechnungsvariante (Grund-/Arbeitspreis bzw. Arbeits-/Leistungspreis&#41;, welche sich aus der Artikel-ID bzw. Gruppenartikel-ID ergibt, falls die Netznutzungsabrech-nungsvariante nicht explizit über entsprechende Codes ausgetauscht wurde?) then (ja)
else (nein)
    :A03;
    note left
        Cluster: Ablehnung
        Der Typ des Lieferscheins ist nicht identisch zur Netznutzungsabrechnungsvariante.
    endnote
    kill;
endif
if (<b>4: </b> Handelt es sich um einen Lieferschein vom Typ „Grund-/ Arbeitspreis“?) then (ja)
    if (<b>5: </b> Liegt in dem Lieferschein genannten Zeitraum mindestens ein Tag eines noch nicht stornierten Lieferscheins?) then (ja)
        :A04;
        note left
            Cluster: Ablehnung
            Überschneidender Zeitraum in noch nicht stornierten Lieferscheinen „Arbeits-/Grundpreis“
        endnote
        kill;
    else (nein)
    endif
    if (<b>6: </b> Handelt es sich um eine Marktlokation mit der messtechnischen Einordnung „keine Messung“ (pauschale Marktlokation&#41;?) then (ja)
        if (<b>7: </b> Entspricht die im Lieferschein übermittelte Energiemenge der Energiemenge, welche sich aus der zuvor für den Zeitraum ausgetauschten Jahresverbrauchsprognose ergibt?) then (ja)
        else (nein)
            :A06;
            note left
                Cluster: Ablehnung
                Energiemenge für pauschale Marktlokation stimmt nicht überein.
            endnote
            kill;
        endif
    else (nein)
        if (<b>8: </b> Liegen nach Reklamation beim MSB für den korrespondierenden Zeitraum des Lieferscheins die Energiemengen an der Marktlokation vom MSB vor?
Hinweis: Sollten die Energiemengen an der Marktlokation vom MSB für den korrespondierenden Zeitraum nicht vorliegen, müssen diese erst vom LF beim MSB reklamiert worden sein, bevor diese Frage mit nein beantwortet werden darf.) then (ja)
        else (nein)
            :A07;
            note left
                Cluster: Ablehnung
                Energiemengen vom MSB an der Marktlokation fehlen und sind beim MSB reklamiert
                Hinweis: 
                Die Prüfung des Lieferscheins erfolgt für Leistungszeiträume vor dem 01.12.2019 auf Basis der Werte, die vom NB bzw. vom gMSB übermittelt wurden.
                Siehe Mitteilung Nr. 6 zur MaKo 2020 (Az.: BK6-18-032&#41; der Bundesnetzagentur vom 28.01.2020.
            endnote
            kill;
        endif
        if (<b>9: </b> Liegt für den im Lieferschein genannten Zeitraum für eine der genannten OBIS-Kennzahlen eine zusätzliche Energiemenge vor, die noch nicht storniert wurde?) then (ja)
            :A08;
            note left
                Cluster: Ablehnung
                Für einen Zeitabschnitt liegen für mindestens eine OBIS-Kennzahl mehrere Energiemengen vor.
            endnote
            kill;
        else (nein)
        endif
        if (<b>10: </b> Entspricht die zuvor vom MSB übermittelte Summe der Energiemengen je OBIS-Kennzahl der Summe der Energiemengen der aus dem Lieferschein korrespondierenden OBIS-Kennzahl für den vom Lieferschein abgedeckten Zeitraum?) then (ja)
        else (nein)
            if (<b>11: </b> Handelt es sich um eine Marktlokation, deren Netznutzung aufgrund vertraglicher Vereinbarungen abweichend zu den in GPKE Teil 2 Kapitel 3.2.2 beschriebenen Regelungen abgerechnet wird?) then (ja)
                if (<b>12: </b> Entspricht die im Lieferschein übermittelte Energiemenge der Energiemenge, welche sich auf Basis der vertraglichen Vereinbarungen ergibt?) then (ja)
                else (nein)
                    :A09;
                    note left
                        Cluster: Ablehnung
                        Energiemenge widerspricht vertraglich vereinbarter Logik.
                    endnote
                    kill;
                endif
            else (nein)
                if (<b>13: </b> Entspricht die zuvor vom MSB übermittelte Summe der Energiemengen der Summe der Energiemengen aus dem Lieferschein für den vom Lieferschein abgedeckten Zeit-raum?) then (ja)
                else (nein)
                    :A10;
                    note left
                        Cluster: Ablehnung
                        Energiemengen stimmen nicht überein.
                    endnote
                    kill;
                endif
            endif
        endif
    endif
else (nein)
    if (<b>14: </b> Handelt es sich um eine Marktlokation mit der messtech-nischen Einordnung „keine Messung“ (pauschale Markt-lokation&#41;?) then (ja)
        if (<b>15: </b> Entspricht die Energiemenge aus dem Lieferschein den bilateral vertraglichen Vereinbarungen?) then (ja)
        else (nein)
            :A11;
            note left
                Cluster: Ablehnung
                Energiemenge für pauschale Marktlokation stimmt nicht überein.
            endnote
            kill;
        endif
    else (nein)
        if (<b>16: </b> Liegen nach Reklamation für den korrespondierenden Zeit-raum des Lieferscheins die Lastgänge an der Marktlokation vom MSB und ggf. das Leistungsmaximum (bei iMS vom MSB, bei kME mit RLM aus Lastgang vom LF entnommen und bei einem unterjährigen Lieferantenwechsel vom NB&#41; vor?
Hinweis: Sollten die Lastgänge an der Marktlokation vom MSB für den korrespondierenden Zeitraum des Lieferscheins nicht vorliegen, müssen diese erst vom LF beim MSB reklamiert worden sein, bevor diese Frage mit nein beantwortet werden darf.) then (ja)
        else (nein)
            :A12;
            note left
                Cluster: Ablehnung
                Lastgänge vom MSB an der Marktlokation fehlen und sind beim MSB reklamiert oder vom NB fehlt die Nachricht „Arbeit und Leistungsmaximum Kalenderjahr vor Lieferbeginn".
            endnote
            kill;
        endif
        if (<b>17: </b> Handelt es sich um eine Marktlokation, deren Netznutzung aufgrund vertraglicher Vereinbarungen abweichend zu den in GPKE Teil 2 Kapitel 3.2.2 beschriebenen Regelungen abgerechnet wird?) then (ja)
            if (<b>18: </b> Entspricht die Energiemenge bzw. das Leistungsmaximum aus dem Lieferschein den bilateral vertraglichen Vereinbarungen?) then (ja)
            else (nein)
                :A13;
                note left
                    Cluster: Ablehnung
                    Energiemenge bzw. Leistungsmaximum aus dem Lieferschein entspricht nicht der vertraglich vereinbarten Energiemenge.
                endnote
                kill;
            endif
        else (nein)
            if (<b>19: </b> Handelt es sich um eine Marktlokation mit der messtechnischen Einordnung „iMS“?) then (ja)
                if (<b>20: </b> Entspricht das im Lieferschein übermittelte Leistungsmaximum dem Leistungsmaximum, das zuvor vom MSB über-mittelt wurde oder dem Leistungsmaximum, welches bei einem unterjährigen Lieferantenwechsel vom NB an den LF übermittelt wurde?) then (ja)
                else (nein)
                    :A14;
                    note left
                        Cluster: Ablehnung
                        Leistungsmaximum aus dem Lieferschein ist nicht identisch zum vorliegenden Leistungsmaximum.
                    endnote
                    kill;
                endif
                if (<b>22: </b> Entspricht jede auf dem Lieferschein vorkommende Energiemenge je Position (OBIS-Kennzahl und Zeitraum&#41; einer Summe der vom MSB zuvor übermittelten ¼ h-Werte unter Berücksichtigung von möglichen kaufmännischen Rundungen, wobei ggf. die Energiemengen aus den bisher gemessenen Arbeits- und Leistungswerten des NB berücksichtigt wurden?) then (ja)
                else (nein)
                    :A16;
                    note left
                        Cluster: Ablehnung
                        Energiemenge aus dem Lieferschein entspricht nicht der Summe aus dem Lastgang.
                    endnote
                    kill;
                endif
            else (nein)
                if (<b>21: </b> Entspricht das im Lieferschein übermittelte Leistungsmaximum dem vorliegenden Leistungsmaximum beim LF, welches aus dem Lastgang vom MSB entnommen oder das Leistungsmaximum, welches bei einem unterjährigen Lieferantenwechsel vom NB an den LF übermittelt wurde?) then (ja)
                else (nein)
                    :A15;
                    note left
                        Cluster: Ablehnung
                        Leistungsmaximum unplausibel
                    endnote
                    kill;
                endif
                if (<b>22: </b> Entspricht jede auf dem Lieferschein vorkommende Energiemenge je Position (OBIS-Kennzahl und Zeitraum&#41; einer Summe der vom MSB zuvor übermittelten ¼ h-Werte unter Berücksichtigung von möglichen kaufmännischen Rundungen, wobei ggf. die Energiemengen aus den bisher gemessenen Arbeits- und Leistungswerten des NB berücksichtigt wurden?) then (ja)
                else (nein)
                    :A16;
                    note left
                        Cluster: Ablehnung
                        Energiemenge aus dem Lieferschein entspricht nicht der Summe aus dem Lastgang.
                    endnote
                    kill;
                endif
            endif
            if (<b>22: </b> Entspricht jede auf dem Lieferschein vorkommende Energiemenge je Position (OBIS-Kennzahl und Zeitraum&#41; einer Summe der vom MSB zuvor übermittelten ¼ h-Werte unter Berücksichtigung von möglichen kaufmännischen Rundungen, wobei ggf. die Energiemengen aus den bisher gemessenen Arbeits- und Leistungswerten des NB berücksichtigt wurden?) then (ja)
            else (nein)
                :A16;
                note left
                    Cluster: Ablehnung
                    Energiemenge aus dem Lieferschein entspricht nicht der Summe aus dem Lastgang.
                endnote
                kill;
            endif
        endif
    endif
endif
:A05;
note left
    Cluster: Zustimmung
    Zustimmung
endnote
kill;

@enduml
