@startuml
skinparam Shadowing false
skinparam NoteBorderColor #f3f1f6
skinparam NoteBackgroundColor #f3f1f6
skinparam NoteFontSize 12
skinparam ActivityBorderColor none
skinparam ActivityBackgroundColor #7a8da1
skinparam ActivityFontSize 16
skinparam ArrowColor #7aab8a
skinparam ArrowFontSize 16
skinparam ActivityDiamondBackgroundColor #7aab8a
skinparam ActivityDiamondBorderColor #7aab8a
skinparam ActivityDiamondFontSize 18
skinparam defaultFontName DejaVu Serif Condensed
skinparam ActivityEndColor #669580

header
<b>FV2210
2022-12-12
endheader

title
GPKE

6.49.2: AD: Steuerbefehl vom LF an MSB



end title
:<b>E_0565</b>;
note right
<b><i>Prüfende Rolle: MSB
end note

if (<b>10: </b> War eine Verarbeitung im Backend des MSB möglich?) then (ja)
else (nein)
    :A01;
    note left
        Backend des MSB ist überlastet.
    endnote
    kill;
endif
if (<b>20: </b> War eine Kommunikationsverbindung zur Steuerbox möglich?) then (ja)
else (nein)
    :A02;
    note left
        Kommunikationsverbindung zur Steuerbox ist gestört.
    endnote
    kill;
endif
if (<b>30: </b> War es prozessual möglich den Steuerbefehl umzusetzen?) then (ja)
    :A04;
    note left
        Der Steuerbefehl kann grundsätzlich umgesetzt werden.
    endnote
    kill;
else (nein)
    :A03;
    note left
        Prozessual ist es derzeit nicht möglich die Anforderung umzusetzen (z.B. aufgrund von Wartungsarbeiten&#41;.
    endnote
    kill;
endif

@enduml
