@startuml
skinparam Shadowing false
skinparam NoteBorderColor #f3f1f6
skinparam NoteBackgroundColor #f3f1f6
skinparam NoteFontSize 12
skinparam ActivityBorderColor none
skinparam ActivityBackgroundColor #7a8da1
skinparam ActivityFontSize 16
skinparam ArrowColor #7aab8a
skinparam ArrowFontSize 16
skinparam ActivityDiamondBackgroundColor #7aab8a
skinparam ActivityDiamondBorderColor #7aab8a
skinparam ActivityDiamondFontSize 18
skinparam defaultFontName DejaVu Serif Condensed
skinparam ActivityEndColor #669580

header
<b>FV2210
2022-12-12
endheader

title
GPKE

6.6.1: AD: Lieferbeginn



end title
:<b>E_0622</b>;
note right
<b><i>Prüfende Rolle: NB
end note

if (<b>10: </b> Wurde der Anwendungsfall für eine verbrauchende Marktlokation oder ruhende Marktlokation verwendet?) then (ja)
    if (<b>15: </b> Wurde die Vorlauffrist eingehalten?) then (ja)
    else (nein)
        :A07;
        note left
            Cluster: Ablehnung
            Vorlauffrist wurde nicht eingehalten
        endnote
        kill;
    endif
    if (<b>16: </b> Ist in dem Anwendungsfall in der Ergänzung zum Transaktionsgrund „Ruhende Marktlokation“ angegeben?) then (ja)
        if (<b>17: </b> Ist die „ruhende Marktlokation“ (SG5 LOC+Z22&#41; messtechnisch mittels iMS erfasst? (Messtechnische Einordung der Marktlokation = iMS&#41;) then (ja)
        else (nein)
            :A36;
            note left
                Cluster: Ablehnung
                Die genannte Marktlokation entspricht nicht den Anforderungen, da messtechnische Einordung nicht iMS.
            endnote
            kill;
        endif
        if (<b>18: </b> Handelt es sich bei der „ruhenden Marktlokation“ (SG5 LOC+Z22&#41; im System des Empfängers um eine verbrauchende Marktlokation?) then (ja)
        else (nein)
            :A09;
            note left
                Cluster: Ablehnung
                Bei der angemeldeten ruhenden Marktlokation handelt es sich nicht um eine verbrauchende Marktlokation
            endnote
            kill;
        endif
        if (<b>19: </b> Soll die angegebene Marktlokation zu einer Neubildung einer Kundenanlage führen (Produktcode: 9991000002769, Code der Produkteigenschaft: 9991000002933&#41;?) then (ja)
        else (nein)
            if (<b>25: </b> Handelt es sich bei der im Anwendungsfall genannten Marktlokation (im SG5 LOC+Z16&#41; um eine Marktlokation „Kundenanlage“ (§ 20 Abs. 1d EnWG bzw. § 10 c EEG&#41;?) then (ja)
            else (nein)
                :A08;
                note left
                    Cluster: Ablehnung
                    Bei der in der Anmeldung genannten Marktlokation (im SG5 LOC+Z16&#41; handelt es sich nicht um eine „Kundenanlage“. Somit kann die zu integrierende Marktlokation (im SG5 LOC+Z22&#41; nicht der Marktlokation „Kundenanlage“ (im SG5 LOC+Z16&#41; zugeordnet werden.
                endnote
                kill;
            endif
            if (<b>26: </b> Befindet sich die „ruhende Marktlokation (SG5 LOC+Z22&#41; hinter der (den&#41; gleichen Netzlokation(en&#41; wie die Marktlokation der Kundenanlage (SG5 LOC+Z16&#41;?) then (ja)
            else (nein)
                :A37;
                note left
                    Cluster: Ablehnung
                    Die zu integrierende Marktlokation befindet sich nicht hinter der /den gleichen Netzlokation(en&#41; liegen, wie die Marktlokation der „Kundenanlage“ („Abbildung von § 20 Abs. 1d EnWG bzw. § 10c EEG“&#41;.
                endnote
                kill;
            endif
            if (<b>30: </b> Nimmt die Marktlokation zum Anmeldedatum an der Marktkommunikation teil?
Hinweis: Marktlokationen, die nicht an der Marktkommunikation teilnehmen, sind Marktlokationen, die stillgelegt sind bzw. Marktlokationen, die dem "Modell 2 zur ladevorgangscharfen bilanziellen Energiemengenzuordnungsmöglichkeit" zugeordnet sind.) then (ja)
            else (nein)
                :A02;
                note left
                    Cluster: Ablehnung
                    Marktlokation, die über Marktlokations-ID identifiziert wurde, nimmt nicht an der Marktkommunikation teil.
                endnote
                kill;
            endif
            if (<b>50: </b> Handelt es sich um eine Anmeldung für eine Neuanlage?
Hinweis: Dies sind Marktlokationen, bei denen der NB den Identifikator schon vergeben hat, deren Inbetriebnahme aber noch in der Zukunft liegt. (somit ein Lieferbeginn noch nicht feststeht&#41;.) then (ja)
                :A04;
                note left
                    Cluster: Ablehnung
                    Falscher Prozess
                endnote
                kill;
            else (nein)
            endif
            if (<b>60: </b> Sind alle zwingend notwendigen Anforderungen des LF erfüllt?
Hinweis: 
Insbesondere die notwendige Zuordnungsermächtigung (Bilanzkreis/Bilanzierungsverfahren&#41; ist vorhanden) then (ja)
            else (nein)
                :A05;
                note left
                    Cluster: Ablehnung
                    Anforderungen können nicht erfüllt werden
                    Hinweis: die Abweichungen sind zu benennen
                endnote
                kill;
            endif
            if (<b>70: </b> Liegt für diese Marktlokation bereits eine gerade in Arbeit befindliche und noch nicht beantwortete Anmeldung vor?) then (ja)
                :A06;
                note left
                    Cluster: Ablehnung
                    Andere Anmeldung in Bearbeitung.
                    Hinweis:
                    Der Zuordnungsbeginn der derzeit in Bearbeitung befindlichen Anmeldung und der Zeitpunkt, ab welchem der NB wieder Anmeldungen für diese Marktlokation entgegennimmt werden übermittelt.
                endnote
                kill;
            else (nein)
            endif
        endif
    else (nein)
    endif
    if (<b>30: </b> Nimmt die Marktlokation zum Anmeldedatum an der Marktkommunikation teil?
Hinweis: Marktlokationen, die nicht an der Marktkommunikation teilnehmen, sind Marktlokationen, die stillgelegt sind bzw. Marktlokationen, die dem "Modell 2 zur ladevorgangscharfen bilanziellen Energiemengenzuordnungsmöglichkeit" zugeordnet sind.) then (ja)
    else (nein)
        :A02;
        note left
            Cluster: Ablehnung
            Marktlokation, die über Marktlokations-ID identifiziert wurde, nimmt nicht an der Marktkommunikation teil.
        endnote
        kill;
    endif
    if (<b>50: </b> Handelt es sich um eine Anmeldung für eine Neuanlage?
Hinweis: Dies sind Marktlokationen, bei denen der NB den Identifikator schon vergeben hat, deren Inbetriebnahme aber noch in der Zukunft liegt. (somit ein Lieferbeginn noch nicht feststeht&#41;.) then (ja)
        :A04;
        note left
            Cluster: Ablehnung
            Falscher Prozess
        endnote
        kill;
    else (nein)
    endif
    if (<b>60: </b> Sind alle zwingend notwendigen Anforderungen des LF erfüllt?
Hinweis: 
Insbesondere die notwendige Zuordnungsermächtigung (Bilanzkreis/Bilanzierungsverfahren&#41; ist vorhanden) then (ja)
    else (nein)
        :A05;
        note left
            Cluster: Ablehnung
            Anforderungen können nicht erfüllt werden
            Hinweis: die Abweichungen sind zu benennen
        endnote
        kill;
    endif
    if (<b>70: </b> Liegt für diese Marktlokation bereits eine gerade in Arbeit befindliche und noch nicht beantwortete Anmeldung vor?) then (ja)
        :A06;
        note left
            Cluster: Ablehnung
            Andere Anmeldung in Bearbeitung.
            Hinweis:
            Der Zuordnungsbeginn der derzeit in Bearbeitung befindlichen Anmeldung und der Zeitpunkt, ab welchem der NB wieder Anmeldungen für diese Marktlokation entgegennimmt werden übermittelt.
        endnote
        kill;
    else (nein)
    endif
else (nein)
    if (<b>220: </b> Handelt es sich um einen „Einzug in Neuanlage“?
Hinweis: Dies sind Marktlokationen, bei denen der NB den Identifikator schon vergeben hat, deren Inbetriebnahme aber noch in der Zukunft liegt (somit ein Lieferbeginn noch nicht feststeht&#41;.) then (ja)
        :A21;
        note left
            Cluster: Ablehnung
            Falscher Prozess
        endnote
        kill;
    else (nein)
    endif
    if (<b>250: </b> Erfolgt die Bilanzierung auf Basis von Viertelstundenwerten? 
Hinweis: In viertelstündlicher Auflösung (verpflichtend lt. EEG&#41;) then (ja)
    else (nein)
        :A24;
        note left
            Cluster: Ablehnung
            Bilanzierung erfolgt nicht auf Basis von Viertelstundenwerten.
        endnote
        kill;
    endif
    if (<b>260: </b> Sind alle zwingend notwendigen Anforderungen des LF erfüllt?
Hinweis: Insbesondere die notwendige Zuordnungsermächtigung (Bilanzkreis/Bilanzierungsverfahren&#41; ist vorhanden) then (ja)
    else (nein)
        :A25;
        note left
            Cluster: Ablehnung
            Anforderungen können nicht erfüllt werden
            Hinweis: die Abweichungen sind zu benennen
        endnote
        kill;
    endif
    if (<b>270: </b> Liegt für diese Marktlokation bereits eine gerade in Arbeit befindliche und noch nicht beantwortete Anmeldung vor?) then (ja)
        :A45;
        note left
            Cluster: Ablehnung
            Andere Anmeldung in Bearbeitung.
            Hinweis:
            Der Zuordnungsbeginn der derzeit in Bearbeitung befindlichen Anmeldung und der Zeitpunkt, ab welchem der NB wieder Anmeldungen für diese Marktlokation entgegennimmt.
        endnote
        kill;
    else (nein)
    endif
    if (<b>300: </b> Handelt es sich um Geschäftsvorfall 1?) then (ja)
        if (<b>400: </b> Verändert sich die im Geschäftsvorfall angegebene Veräußerungsform zum Tag des gewünschten Zuordnungsbeginns (Veräußerungsformwechsel&#41;?) then (ja)
        else (nein)
            if (<b>405: </b> Handelt es sich um eine „Nicht-EEG-/- KWKG“-Marktlokation?) then (ja)
                if (<b>406: </b> Ist der Übertragungstag spätestens der Tag vor dem letzten WT vor dem Zuordnungsbeginn?) then (ja)
                else (nein)
                    :A34;
                    note left
                        Cluster: Ablehnung
                        Die Vorlauffrist für eine „Nicht-EEG-/ - KWKG“- Marktlokation wurde nicht eingehalten.
                    endnote
                    kill;
                endif
            else (nein)
            endif
        endif
        if (<b>410: </b> Ist das angegebene Datum „Lieferbeginn“ der 1. eines Kalendermonats, 00:00 Uhr?) then (ja)
        else (nein)
            :A27;
            note left
                Cluster: Ablehnung
                Vorgaben EEG nicht eingehalten.
            endnote
            kill;
        endif
        if (<b>420: </b> Handelt es sich um einen verkürzten Wechsel?
Hinweis: Vorgabe nach EEG: 5 WT vor Zuordnungsbeginn) then (ja)
            if (<b>440: </b> Ist die Vorlauffrist eingehalten?
(Eingang spätestens 5 WT vor Zuordnungsbeginn&#41;) then (ja)
            else (nein)
                :A29;
                note left
                    Cluster: Ablehnung
                    Die verkürzte Vorlauffrist für EEG-/KWKG- Marktlokationen im Geschäftsvorfall 1 wurden nicht eingehalten (Fristüberschreitung&#41;.
                endnote
                kill;
            endif
        else (nein)
            if (<b>430: </b> Ist die Vorlauffrist von einem Monat eingehalten?) then (ja)
            else (nein)
                :A28;
                note left
                    Cluster: Ablehnung 
                    Die Vorlauffrist für EEG-/KWKG-Marktlokationen im Geschäftsvorfall 1 wurden nicht eingehalten (Fristüberschreitung&#41;.
                endnote
                kill;
            endif
        endif
    else (nein)
        if (<b>310: </b> Handelt es sich um Geschäftsvorfall 2?) then (ja)
            if (<b>600: </b> Verändert sich die im Geschäftsvorfall angegebene Veräußerungsform zum Tag des gewünschten Zuordnungsbeginns (Veräußerungsformwechsel&#41;?) then (ja)
            else (nein)
                if (<b>605: </b> Handelt es sich um eine „Nicht-EEG-/-KWKG“-Marktlokation?) then (ja)
                    if (<b>610: </b> Ist der Übertragungstag spätestens der Tag vor dem letzten WT vor dem Zuordnungsbeginn?) then (ja)
                    else (nein)
                        :A30;
                        note left
                            Cluster: Ablehnung 
                            Die Vorlauffrist für eine „Nicht-EEG-/-KWKG“- Marktlokation im Geschäftsvorfall 2 wurde nicht eingehalten (Fristüberschreitung&#41;.
                        endnote
                        kill;
                    endif
                else (nein)
                endif
            endif
            if (<b>620: </b> Ist das angegebene Datum „Lieferbeginn“ der 1. eines Kalendermonats 00:00 Uhr?) then (ja)
            else (nein)
                :A31;
                note left
                    Cluster: Ablehnung
                    Das Lieferbeginn darf nur der 1. eines Kalendermonats 00:00 Uhr sein
                endnote
                kill;
            endif
            if (<b>630: </b> Ist die Vorlauffrist von einem Monat eingehalten?) then (ja)
            else (nein)
                :A32;
                note left
                    Cluster: Ablehnung
                    Die Vorlauffrist für EEG-/KWKG-Marktlokationen im Geschäftsvorfall 2 wurden nicht eingehalten (Fristüberschreitung&#41;.
                endnote
                kill;
            endif
        else (nein)
            if (<b>800: </b> Ist das angegebene Datum „Lieferbeginn“ der 1. eines Kalendermonats 00:00 Uhr?) then (ja)
            else (nein)
                if (<b>805: </b> Handelt es sich um eine „Nicht-EEG-/-KWKG“-Marktlokation?) then (ja)
                    if (<b>806: </b> Ist der Übertragungstag spätestens der Tag vor dem letzten WT vor dem Zuordnungsbeginn?) then (ja)
                    else (nein)
                        :A35;
                        note left
                            Cluster: Ablehnung
                            Die Vorlauffrist für eine „Nicht-EEG-/-KWKG“- Marktlokation wurde nicht eingehalten.
                        endnote
                        kill;
                    endif
                else (nein)
                endif
            endif
            if (<b>810: </b> Ist die Vorlauffrist von einem Monat eingehalten?) then (ja)
            else (nein)
                :A44;
                note left
                    Cluster: Ablehnung
                    Fristüberschreitung
                endnote
                kill;
            endif
            if (<b>830: </b> Ist der angegebene Prozentsatz an der Marktlokation noch frei?) then (ja)
            else (nein)
                :EBD E_0621_Prüfen, ob Anfrage zur Beendigung der Zuordnung erforderlich
Hinweis: Anfrage zur Beendigung der Zuordnung muss zwingend an alle LFA und an den Anmeldenden versendet werden!;
                kill;
            endif
        endif
    endif
endif
:EBD E_0621_Prüfen, ob Anfrage zur Beendigung der Zuordnung erforderlich;
kill;

@enduml
