@startuml
skinparam Shadowing false
skinparam NoteBorderColor #f3f1f6
skinparam NoteBackgroundColor #f3f1f6
skinparam NoteFontSize 12
skinparam ActivityBorderColor none
skinparam ActivityBackgroundColor #7a8da1
skinparam ActivityFontSize 16
skinparam ArrowColor #7aab8a
skinparam ArrowFontSize 16
skinparam ActivityDiamondBackgroundColor #7aab8a
skinparam ActivityDiamondBorderColor #7aab8a
skinparam ActivityDiamondFontSize 18
skinparam defaultFontName DejaVu Serif Condensed
skinparam ActivityEndColor #669580

header
<b>FV2210
2022-12-12
endheader

footer
v4.1 | 11.12.2025 (urspr. 01.04.2025) | ebdamame v1.0.0 | rebdhuhn v1.0.1
endfooter

title
Redispatch 2.0

16.2.1: AD: Ermittlung und Abstimmung der abrechnungsrelevanten Ausfallarbeit – Planwertmodell



end title
:<b>E_0902</b>;
note right
<b><i>Prüfende Rolle: NB
end note

if (<b>1: </b> Entsprechen die Energiemengen der Ausfallarbeitszeitreihe bzw. der Fahrplananteilzeitreihe den erwarteten Energiemengen?) then (ja)
    :A01;
    note left
        Cluster: Zustimmung
        Zustimmung
    endnote
    kill;
else (nein)
endif
if (<b>2: </b> Kann ein Gegenvorschlag erstellt werden?) then (ja)
    :A02;
    note left
        Cluster: Ablehnung
        Energiemengen falsch / nicht plausibel
        Übermittlung Gegenvorschlag
        Hinweis: Das identifizierte Problem ist in der Antwort zu beschreiben / benennen.
    endnote
    kill;
else (nein)
    :A03;
    note left
        Cluster: Ablehnung
        Energiemengen falsch / nicht plausibel inkl. Korrekturanforderung
        Hinweis: Das identifizierte Problem ist in der Antwort zu beschreiben / benennen.
    endnote
    kill;
endif

@enduml
