@startuml
skinparam Shadowing false
skinparam NoteBorderColor #f3f1f6
skinparam NoteBackgroundColor #f3f1f6
skinparam NoteFontSize 12
skinparam ActivityBorderColor none
skinparam ActivityBackgroundColor #7a8da1
skinparam ActivityFontSize 16
skinparam ArrowColor #7aab8a
skinparam ArrowFontSize 16
skinparam ActivityDiamondBackgroundColor #7aab8a
skinparam ActivityDiamondBorderColor #7aab8a
skinparam ActivityDiamondFontSize 18
skinparam defaultFontName DejaVu Serif Condensed
skinparam ActivityEndColor #669580

header
<b>FV2210
2022-12-12
endheader

footer
v4.1 | 11.12.2025 (urspr. 01.04.2025)
endfooter

title
Sperrprozesse Gas

18.5.1: AD: Wiederherstellung der Anschlussnutzung bei Lieferbeginn



end title
:<b>E_1020</b>;
note right
<b><i>Prüfende Rolle: NB
end note

if (<b>10: </b> Ist die Entsperrung erfolgreich durchgeführt worden?) then (ja)
    :A01;
    note left
        Marktlokation ist entsperrt
    endnote
    kill;
else (nein)
    :Bilaterale Klärung.;
    kill;
endif

@enduml
